'use strict';

module.exports = {
    // Data taken from http://www.downloadexcelfiles.com/gb_en/download-excel-file-list-counties-uk
    uk: [
        { name: 'Bath and North East Somerset' },
        { name: 'Aberdeenshire' },
        { name: 'Anglesey' },
        { name: 'Angus' },
        { name: 'Bedford' },
        { name: 'Blackburn with Darwen' },
        { name: 'Blackpool' },
        { name: 'Bournemouth' },
        { name: 'Bracknell Forest' },
        { name: 'Brighton & Hove' },
        { name: 'Bristol' },
        { name: 'Buckinghamshire' },
        { name: 'Cambridgeshire' },
        { name: 'Carmarthenshire' },
        { name: 'Central Bedfordshire' },
        { name: 'Ceredigion' },
        { name: 'Cheshire East' },
        { name: 'Cheshire West and Chester' },
        { name: 'Clackmannanshire' },
        { name: 'Conwy' },
        { name: 'Cornwall' },
        { name: 'County Antrim' },
        { name: 'County Armagh' },
        { name: 'County Down' },
        { name: 'County Durham' },
        { name: 'County Fermanagh' },
        { name: 'County Londonderry' },
        { name: 'County Tyrone' },
        { name: 'Cumbria' },
        { name: 'Darlington' },
        { name: 'Denbighshire' },
        { name: 'Derby' },
        { name: 'Derbyshire' },
        { name: 'Devon' },
        { name: 'Dorset' },
        { name: 'Dumfries and Galloway' },
        { name: 'Dundee' },
        { name: 'East Lothian' },
        { name: 'East Riding of Yorkshire' },
        { name: 'East Sussex' },
        { name: 'Edinburgh?' },
        { name: 'Essex' },
        { name: 'Falkirk' },
        { name: 'Fife' },
        { name: 'Flintshire' },
        { name: 'Gloucestershire' },
        { name: 'Greater London' },
        { name: 'Greater Manchester' },
        { name: 'Gwent' },
        { name: 'Gwynedd' },
        { name: 'Halton' },
        { name: 'Hampshire' },
        { name: 'Hartlepool' },
        { name: 'Herefordshire' },
        { name: 'Hertfordshire' },
        { name: 'Highlands' },
        { name: 'Hull' },
        { name: 'Isle of Wight' },
        { name: 'Isles of Scilly' },
        { name: 'Kent' },
        { name: 'Lancashire' },
        { name: 'Leicester' },
        { name: 'Leicestershire' },
        { name: 'Lincolnshire' },
        { name: 'Lothian' },
        { name: 'Luton' },
        { name: 'Medway' },
        { name: 'Merseyside' },
        { name: 'Mid Glamorgan' },
        { name: 'Middlesbrough' },
        { name: 'Milton Keynes' },
        { name: 'Monmouthshire' },
        { name: 'Moray' },
        { name: 'Norfolk' },
        { name: 'North East Lincolnshire' },
        { name: 'North Lincolnshire' },
        { name: 'North Somerset' },
        { name: 'North Yorkshire' },
        { name: 'Northamptonshire' },
        { name: 'Northumberland' },
        { name: 'Nottingham' },
        { name: 'Nottinghamshire' },
        { name: 'Oxfordshire' },
        { name: 'Pembrokeshire' },
        { name: 'Perth and Kinross' },
        { name: 'Peterborough' },
        { name: 'Plymouth' },
        { name: 'Poole' },
        { name: 'Portsmouth' },
        { name: 'Powys' },
        { name: 'Reading' },
        { name: 'Redcar and Cleveland' },
        { name: 'Rutland' },
        { name: 'Scottish Borders' },
        { name: 'Shropshire' },
        { name: 'Slough' },
        { name: 'Somerset' },
        { name: 'South Glamorgan' },
        { name: 'South Gloucestershire' },
        { name: 'South Yorkshire' },
        { name: 'Southampton' },
        { name: 'Southend-on-Sea' },
        { name: 'Staffordshire' },
        { name: 'Stirlingshire' },
        { name: 'Stockton-on-Tees' },
        { name: 'Stoke-on-Trent' },
        { name: 'Strathclyde' },
        { name: 'Suffolk' },
        { name: 'Surrey' },
        { name: 'Swindon' },
        { name: 'Telford and Wrekin' },
        { name: 'Thurrock' },
        { name: 'Torbay' },
        { name: 'Tyne and Wear' },
        { name: 'Warrington' },
        { name: 'Warwickshire' },
        { name: 'West Berkshire' },
        { name: 'West Glamorgan' },
        { name: 'West Lothian' },
        { name: 'West Midlands' },
        { name: 'West Sussex' },
        { name: 'West Yorkshire' },
        { name: 'Western Isles' },
        { name: 'Wiltshire' },
        { name: 'Windsor and Maidenhead' },
        { name: 'Wokingham' },
        { name: 'Worcestershire' },
        { name: 'Wrexham' },
        { name: 'York' }]
};
