'use strict';

module.exports = {
    it: [
        { name: "Valle d'Aosta", abbreviation: 'VDA' },
        { name: 'Piemonte', abbreviation: 'PIE' },
        { name: 'Lombardia', abbreviation: 'LOM' },
        { name: 'Veneto', abbreviation: 'VEN' },
        { name: 'Trentino Alto Adige', abbreviation: 'TAA' },
        { name: 'Friuli Venezia Giulia', abbreviation: 'FVG' },
        { name: 'Liguria', abbreviation: 'LIG' },
        { name: 'Emilia Romagna', abbreviation: 'EMR' },
        { name: 'Toscana', abbreviation: 'TOS' },
        { name: 'Umbria', abbreviation: 'UMB' },
        { name: 'Marche', abbreviation: 'MAR' },
        { name: 'Abruzzo', abbreviation: 'ABR' },
        { name: 'Lazio', abbreviation: 'LAZ' },
        { name: 'Campania', abbreviation: 'CAM' },
        { name: 'Puglia', abbreviation: 'PUG' },
        { name: 'Basilicata', abbreviation: 'BAS' },
        { name: 'Molise', abbreviation: 'MOL' },
        { name: 'Calabria', abbreviation: 'CAL' },
        { name: 'Sicilia', abbreviation: 'SIC' },
        { name: 'Sardegna', abbreviation: 'SAR' }
    ],
    mx: [
        { name: 'Aguascalientes', abbreviation: 'AGU' },
        { name: 'Baja California', abbreviation: 'BCN' },
        { name: 'Baja California Sur', abbreviation: 'BCS' },
        { name: 'Campeche', abbreviation: 'CAM' },
        { name: 'Chiapas', abbreviation: 'CHP' },
        { name: 'Chihuahua', abbreviation: 'CHH' },
        { name: 'Ciudad de México', abbreviation: 'DIF' },
        { name: 'Coahuila', abbreviation: 'COA' },
        { name: 'Colima', abbreviation: 'COL' },
        { name: 'Durango', abbreviation: 'DUR' },
        { name: 'Guanajuato', abbreviation: 'GUA' },
        { name: 'Guerrero', abbreviation: 'GRO' },
        { name: 'Hidalgo', abbreviation: 'HID' },
        { name: 'Jalisco', abbreviation: 'JAL' },
        { name: 'México', abbreviation: 'MEX' },
        { name: 'Michoacán', abbreviation: 'MIC' },
        { name: 'Morelos', abbreviation: 'MOR' },
        { name: 'Nayarit', abbreviation: 'NAY' },
        { name: 'Nuevo León', abbreviation: 'NLE' },
        { name: 'Oaxaca', abbreviation: 'OAX' },
        { name: 'Puebla', abbreviation: 'PUE' },
        { name: 'Querétaro', abbreviation: 'QUE' },
        { name: 'Quintana Roo', abbreviation: 'ROO' },
        { name: 'San Luis Potosí', abbreviation: 'SLP' },
        { name: 'Sinaloa', abbreviation: 'SIN' },
        { name: 'Sonora', abbreviation: 'SON' },
        { name: 'Tabasco', abbreviation: 'TAB' },
        { name: 'Tamaulipas', abbreviation: 'TAM' },
        { name: 'Tlaxcala', abbreviation: 'TLA' },
        { name: 'Veracruz', abbreviation: 'VER' },
        { name: 'Yucatán', abbreviation: 'YUC' },
        { name: 'Zacatecas', abbreviation: 'ZAC' }
    ]
};
