'use strict';

module.exports = [
    'Airline Pilot',
    'Academic Team',
    'Accountant',
    'Account Executive',
    'Actor',
    'Actuary',
    'Acquisition Analyst',
    'Administrative Asst.',
    'Administrative Analyst',
    'Administrator',
    'Advertising Director',
    'Aerospace Engineer',
    'Agent',
    'Agricultural Inspector',
    'Agricultural Scientist',
    'Air Traffic Controller',
    'Animal Trainer',
    'Anthropologist',
    'Appraiser',
    'Architect',
    'Art Director',
    'Artist',
    'Astronomer',
    'Athletic Coach',
    'Auditor',
    'Author',
    'Baker',
    'Banker',
    'Bankruptcy Attorney',
    'Benefits Manager',
    'Biologist',
    'Bio-feedback Specialist',
    'Biomedical Engineer',
    'Biotechnical Researcher',
    'Broadcaster',
    'Broker',
    'Building Manager',
    'Building Contractor',
    'Building Inspector',
    'Business Analyst',
    'Business Planner',
    'Business Manager',
    'Buyer',
    'Call Center Manager',
    'Career Counselor',
    'Cash Manager',
    'Ceramic Engineer',
    'Chief Executive Officer',
    'Chief Operation Officer',
    'Chef',
    'Chemical Engineer',
    'Chemist',
    'Child Care Manager',
    'Chief Medical Officer',
    'Chiropractor',
    'Cinematographer',
    'City Housing Manager',
    'City Manager',
    'Civil Engineer',
    'Claims Manager',
    'Clinical Research Assistant',
    'Collections Manager',
    'Compliance Manager',
    'Comptroller',
    'Computer Manager',
    'Commercial Artist',
    'Communications Affairs Director',
    'Communications Director',
    'Communications Engineer',
    'Compensation Analyst',
    'Computer Programmer',
    'Computer Ops. Manager',
    'Computer Engineer',
    'Computer Operator',
    'Computer Graphics Specialist',
    'Construction Engineer',
    'Construction Manager',
    'Consultant',
    'Consumer Relations Manager',
    'Contract Administrator',
    'Copyright Attorney',
    'Copywriter',
    'Corporate Planner',
    'Corrections Officer',
    'Cosmetologist',
    'Credit Analyst',
    'Cruise Director',
    'Chief Information Officer',
    'Chief Technology Officer',
    'Customer Service Manager',
    'Cryptologist',
    'Dancer',
    'Data Security Manager',
    'Database Manager',
    'Day Care Instructor',
    'Dentist',
    'Designer',
    'Design Engineer',
    'Desktop Publisher',
    'Developer',
    'Development Officer',
    'Diamond Merchant',
    'Dietitian',
    'Direct Marketer',
    'Director',
    'Distribution Manager',
    'Diversity Manager',
    'Economist',
    'EEO Compliance Manager',
    'Editor',
    'Education Adminator',
    'Electrical Engineer',
    'Electro Optical Engineer',
    'Electronics Engineer',
    'Embassy Management',
    'Employment Agent',
    'Engineer Technician',
    'Entrepreneur',
    'Environmental Analyst',
    'Environmental Attorney',
    'Environmental Engineer',
    'Environmental Specialist',
    'Escrow Officer',
    'Estimator',
    'Executive Assistant',
    'Executive Director',
    'Executive Recruiter',
    'Facilities Manager',
    'Family Counselor',
    'Fashion Events Manager',
    'Fashion Merchandiser',
    'Fast Food Manager',
    'Film Producer',
    'Film Production Assistant',
    'Financial Analyst',
    'Financial Planner',
    'Financier',
    'Fine Artist',
    'Wildlife Specialist',
    'Fitness Consultant',
    'Flight Attendant',
    'Flight Engineer',
    'Floral Designer',
    'Food & Beverage Director',
    'Food Service Manager',
    'Forestry Technician',
    'Franchise Management',
    'Franchise Sales',
    'Fraud Investigator',
    'Freelance Writer',
    'Fund Raiser',
    'General Manager',
    'Geologist',
    'General Counsel',
    'Geriatric Specialist',
    'Gerontologist',
    'Glamour Photographer',
    'Golf Club Manager',
    'Gourmet Chef',
    'Graphic Designer',
    'Grounds Keeper',
    'Hazardous Waste Manager',
    'Health Care Manager',
    'Health Therapist',
    'Health Service Administrator',
    'Hearing Officer',
    'Home Economist',
    'Horticulturist',
    'Hospital Administrator',
    'Hotel Manager',
    'Human Resources Manager',
    'Importer',
    'Industrial Designer',
    'Industrial Engineer',
    'Information Director',
    'Inside Sales',
    'Insurance Adjuster',
    'Interior Decorator',
    'Internal Controls Director',
    'International Acct.',
    'International Courier',
    'International Lawyer',
    'Interpreter',
    'Investigator',
    'Investment Banker',
    'Investment Manager',
    'IT Architect',
    'IT Project Manager',
    'IT Systems Analyst',
    'Jeweler',
    'Joint Venture Manager',
    'Journalist',
    'Labor Negotiator',
    'Labor Organizer',
    'Labor Relations Manager',
    'Lab Services Director',
    'Lab Technician',
    'Land Developer',
    'Landscape Architect',
    'Law Enforcement Officer',
    'Lawyer',
    'Lead Software Engineer',
    'Lead Software Test Engineer',
    'Leasing Manager',
    'Legal Secretary',
    'Library Manager',
    'Litigation Attorney',
    'Loan Officer',
    'Lobbyist',
    'Logistics Manager',
    'Maintenance Manager',
    'Management Consultant',
    'Managed Care Director',
    'Managing Partner',
    'Manufacturing Director',
    'Manpower Planner',
    'Marine Biologist',
    'Market Res. Analyst',
    'Marketing Director',
    'Materials Manager',
    'Mathematician',
    'Membership Chairman',
    'Mechanic',
    'Mechanical Engineer',
    'Media Buyer',
    'Medical Investor',
    'Medical Secretary',
    'Medical Technician',
    'Mental Health Counselor',
    'Merchandiser',
    'Metallurgical Engineering',
    'Meteorologist',
    'Microbiologist',
    'MIS Manager',
    'Motion Picture Director',
    'Multimedia Director',
    'Musician',
    'Network Administrator',
    'Network Specialist',
    'Network Operator',
    'New Product Manager',
    'Novelist',
    'Nuclear Engineer',
    'Nuclear Specialist',
    'Nutritionist',
    'Nursing Administrator',
    'Occupational Therapist',
    'Oceanographer',
    'Office Manager',
    'Operations Manager',
    'Operations Research Director',
    'Optical Technician',
    'Optometrist',
    'Organizational Development Manager',
    'Outplacement Specialist',
    'Paralegal',
    'Park Ranger',
    'Patent Attorney',
    'Payroll Specialist',
    'Personnel Specialist',
    'Petroleum Engineer',
    'Pharmacist',
    'Photographer',
    'Physical Therapist',
    'Physician',
    'Physician Assistant',
    'Physicist',
    'Planning Director',
    'Podiatrist',
    'Political Analyst',
    'Political Scientist',
    'Politician',
    'Portfolio Manager',
    'Preschool Management',
    'Preschool Teacher',
    'Principal',
    'Private Banker',
    'Private Investigator',
    'Probation Officer',
    'Process Engineer',
    'Producer',
    'Product Manager',
    'Product Engineer',
    'Production Engineer',
    'Production Planner',
    'Professional Athlete',
    'Professional Coach',
    'Professor',
    'Project Engineer',
    'Project Manager',
    'Program Manager',
    'Property Manager',
    'Public Administrator',
    'Public Safety Director',
    'PR Specialist',
    'Publisher',
    'Purchasing Agent',
    'Publishing Director',
    'Quality Assurance Specialist',
    'Quality Control Engineer',
    'Quality Control Inspector',
    'Radiology Manager',
    'Railroad Engineer',
    'Real Estate Broker',
    'Recreational Director',
    'Recruiter',
    'Redevelopment Specialist',
    'Regulatory Affairs Manager',
    'Registered Nurse',
    'Rehabilitation Counselor',
    'Relocation Manager',
    'Reporter',
    'Research Specialist',
    'Restaurant Manager',
    'Retail Store Manager',
    'Risk Analyst',
    'Safety Engineer',
    'Sales Engineer',
    'Sales Trainer',
    'Sales Promotion Manager',
    'Sales Representative',
    'Sales Manager',
    'Service Manager',
    'Sanitation Engineer',
    'Scientific Programmer',
    'Scientific Writer',
    'Securities Analyst',
    'Security Consultant',
    'Security Director',
    'Seminar Presenter',
    "Ship's Officer",
    'Singer',
    'Social Director',
    'Social Program Planner',
    'Social Research',
    'Social Scientist',
    'Social Worker',
    'Sociologist',
    'Software Developer',
    'Software Engineer',
    'Software Test Engineer',
    'Soil Scientist',
    'Special Events Manager',
    'Special Education Teacher',
    'Special Projects Director',
    'Speech Pathologist',
    'Speech Writer',
    'Sports Event Manager',
    'Statistician',
    'Store Manager',
    'Strategic Alliance Director',
    'Strategic Planning Director',
    'Stress Reduction Specialist',
    'Stockbroker',
    'Surveyor',
    'Structural Engineer',
    'Superintendent',
    'Supply Chain Director',
    'System Engineer',
    'Systems Analyst',
    'Systems Programmer',
    'System Administrator',
    'Tax Specialist',
    'Teacher',
    'Technical Support Specialist',
    'Technical Illustrator',
    'Technical Writer',
    'Technology Director',
    'Telecom Analyst',
    'Telemarketer',
    'Theatrical Director',
    'Title Examiner',
    'Tour Escort',
    'Tour Guide Director',
    'Traffic Manager',
    'Trainer Translator',
    'Transportation Manager',
    'Travel Agent',
    'Treasurer',
    'TV Programmer',
    'Underwriter',
    'Union Representative',
    'University Administrator',
    'University Dean',
    'Urban Planner',
    'Veterinarian',
    'Vendor Relations Director',
    'Viticulturist',
    'Warehouse Manager'
];
