'use strict';

module.exports = {
    us: [
        { name: 'Avenue', abbreviation: 'Ave' },
        { name: 'Boulevard', abbreviation: 'Blvd' },
        { name: 'Center', abbreviation: 'Ctr' },
        { name: 'Circle', abbreviation: 'Cir' },
        { name: 'Court', abbreviation: 'Ct' },
        { name: 'Drive', abbreviation: 'Dr' },
        { name: 'Extension', abbreviation: 'Ext' },
        { name: 'Glen', abbreviation: 'Gln' },
        { name: 'Grove', abbreviation: 'Grv' },
        { name: 'Heights', abbreviation: 'Hts' },
        { name: 'Highway', abbreviation: 'Hwy' },
        { name: 'Junction', abbreviation: 'Jct' },
        { name: 'Key', abbreviation: 'Key' },
        { name: 'Lane', abbreviation: 'Ln' },
        { name: 'Loop', abbreviation: 'Loop' },
        { name: 'Manor', abbreviation: 'Mnr' },
        { name: 'Mill', abbreviation: 'Mill' },
        { name: 'Park', abbreviation: 'Park' },
        { name: 'Parkway', abbreviation: 'Pkwy' },
        { name: 'Pass', abbreviation: 'Pass' },
        { name: 'Path', abbreviation: 'Path' },
        { name: 'Pike', abbreviation: 'Pike' },
        { name: 'Place', abbreviation: 'Pl' },
        { name: 'Plaza', abbreviation: 'Plz' },
        { name: 'Point', abbreviation: 'Pt' },
        { name: 'Ridge', abbreviation: 'Rdg' },
        { name: 'River', abbreviation: 'Riv' },
        { name: 'Road', abbreviation: 'Rd' },
        { name: 'Square', abbreviation: 'Sq' },
        { name: 'Street', abbreviation: 'St' },
        { name: 'Terrace', abbreviation: 'Ter' },
        { name: 'Trail', abbreviation: 'Trl' },
        { name: 'Turnpike', abbreviation: 'Tpke' },
        { name: 'View', abbreviation: 'Vw' },
        { name: 'Way', abbreviation: 'Way' }
    ],
    it: [
        { name: 'Accesso', abbreviation: 'Acc.' },
        { name: 'Alzaia', abbreviation: 'Alz.' },
        { name: 'Arco', abbreviation: 'Arco' },
        { name: 'Archivolto', abbreviation: 'Acv.' },
        { name: 'Arena', abbreviation: 'Arena' },
        { name: 'Argine', abbreviation: 'Argine' },
        { name: 'Bacino', abbreviation: 'Bacino' },
        { name: 'Banchi', abbreviation: 'Banchi' },
        { name: 'Banchina', abbreviation: 'Ban.' },
        { name: 'Bastioni', abbreviation: 'Bas.' },
        { name: 'Belvedere', abbreviation: 'Belv.' },
        { name: 'Borgata', abbreviation: 'B.ta' },
        { name: 'Borgo', abbreviation: 'B.go' },
        { name: 'Calata', abbreviation: 'Cal.' },
        { name: 'Calle', abbreviation: 'Calle' },
        { name: 'Campiello', abbreviation: 'Cam.' },
        { name: 'Campo', abbreviation: 'Cam.' },
        { name: 'Canale', abbreviation: 'Can.' },
        { name: 'Carraia', abbreviation: 'Carr.' },
        { name: 'Cascina', abbreviation: 'Cascina' },
        { name: 'Case sparse', abbreviation: 'c.s.' },
        { name: 'Cavalcavia', abbreviation: 'Cv.' },
        { name: 'Circonvallazione', abbreviation: 'Cv.' },
        { name: 'Complanare', abbreviation: 'C.re' },
        { name: 'Contrada', abbreviation: 'C.da' },
        { name: 'Corso', abbreviation: 'C.so' },
        { name: 'Corte', abbreviation: 'C.te' },
        { name: 'Cortile', abbreviation: 'C.le' },
        { name: 'Diramazione', abbreviation: 'Dir.' },
        { name: 'Fondaco', abbreviation: 'F.co' },
        { name: 'Fondamenta', abbreviation: 'F.ta' },
        { name: 'Fondo', abbreviation: 'F.do' },
        { name: 'Frazione', abbreviation: 'Fr.' },
        { name: 'Isola', abbreviation: 'Is.' },
        { name: 'Largo', abbreviation: 'L.go' },
        { name: 'Litoranea', abbreviation: 'Lit.' },
        { name: 'Lungolago', abbreviation: 'L.go lago' },
        { name: 'Lungo Po', abbreviation: 'l.go Po' },
        { name: 'Molo', abbreviation: 'Molo' },
        { name: 'Mura', abbreviation: 'Mura' },
        { name: 'Passaggio privato', abbreviation: 'pass. priv.' },
        { name: 'Passeggiata', abbreviation: 'Pass.' },
        { name: 'Piazza', abbreviation: 'P.zza' },
        { name: 'Piazzale', abbreviation: 'P.le' },
        { name: 'Ponte', abbreviation: 'P.te' },
        { name: 'Portico', abbreviation: 'P.co' },
        { name: 'Rampa', abbreviation: 'Rampa' },
        { name: 'Regione', abbreviation: 'Reg.' },
        { name: 'Rione', abbreviation: 'R.ne' },
        { name: 'Rio', abbreviation: 'Rio' },
        { name: 'Ripa', abbreviation: 'Ripa' },
        { name: 'Riva', abbreviation: 'Riva' },
        { name: 'Rondò', abbreviation: 'Rondò' },
        { name: 'Rotonda', abbreviation: 'Rot.' },
        { name: 'Sagrato', abbreviation: 'Sagr.' },
        { name: 'Salita', abbreviation: 'Sal.' },
        { name: 'Scalinata', abbreviation: 'Scal.' },
        { name: 'Scalone', abbreviation: 'Scal.' },
        { name: 'Slargo', abbreviation: 'Sl.' },
        { name: 'Sottoportico', abbreviation: 'Sott.' },
        { name: 'Strada', abbreviation: 'Str.' },
        { name: 'Stradale', abbreviation: 'Str.le' },
        { name: 'Strettoia', abbreviation: 'Strett.' },
        { name: 'Traversa', abbreviation: 'Trav.' },
        { name: 'Via', abbreviation: 'V.' },
        { name: 'Viale', abbreviation: 'V.le' },
        { name: 'Vicinale', abbreviation: 'Vic.le' },
        { name: 'Vicolo', abbreviation: 'Vic.' }
    ],
    uk: [
        { name: 'Avenue', abbreviation: 'Ave' },
        { name: 'Close', abbreviation: 'Cl' },
        { name: 'Court', abbreviation: 'Ct' },
        { name: 'Crescent', abbreviation: 'Cr' },
        { name: 'Drive', abbreviation: 'Dr' },
        { name: 'Garden', abbreviation: 'Gdn' },
        { name: 'Gardens', abbreviation: 'Gdns' },
        { name: 'Green', abbreviation: 'Gn' },
        { name: 'Grove', abbreviation: 'Gr' },
        { name: 'Lane', abbreviation: 'Ln' },
        { name: 'Mount', abbreviation: 'Mt' },
        { name: 'Place', abbreviation: 'Pl' },
        { name: 'Park', abbreviation: 'Pk' },
        { name: 'Ridge', abbreviation: 'Rdg' },
        { name: 'Road', abbreviation: 'Rd' },
        { name: 'Square', abbreviation: 'Sq' },
        { name: 'Street', abbreviation: 'St' },
        { name: 'Terrace', abbreviation: 'Ter' },
        { name: 'Valley', abbreviation: 'Val' }
    ]
};
